/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CartItemId = IDL.Nat;
export const ProductId = IDL.Nat;
export const BomType = IDL.Variant({
  'kit' : IDL.Null,
  'accessory' : IDL.Null,
  'base' : IDL.Null,
  'structure' : IDL.Null,
  'wall' : IDL.Null,
  'decal' : IDL.Null,
});
export const Scale = IDL.Variant({ 'scale1_64' : IDL.Null });
export const Category = IDL.Variant({
  'kit' : IDL.Null,
  'accessory' : IDL.Null,
  'base' : IDL.Null,
  'structure' : IDL.Null,
  'wall' : IDL.Null,
  'decal' : IDL.Null,
});
export const Environment = IDL.Variant({
  'indianGarage' : IDL.Null,
  'indianFuelStation' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'stlUrl' : IDL.Opt(IDL.Text),
  'bomType' : BomType,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'scale' : Scale,
  'thumbnailPlaceholder' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
  'environments' : IDL.Vec(Environment),
});
export const BomItem = IDL.Record({
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
  'totalPrice' : IDL.Nat,
  'product' : Product,
});
export const Transform3D = IDL.Record({
  'posX' : IDL.Float64,
  'posY' : IDL.Float64,
  'posZ' : IDL.Float64,
  'rotX' : IDL.Float64,
  'rotY' : IDL.Float64,
  'rotZ' : IDL.Float64,
});
export const KitItem = IDL.Record({
  'transform' : IDL.Opt(Transform3D),
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const ConfiguredKit = IDL.Record({
  'bom' : IDL.Vec(BomItem),
  'name' : IDL.Text,
  'scale' : Scale,
  'environment' : Environment,
  'items' : IDL.Vec(KitItem),
  'totalPrice' : IDL.Nat,
});
export const CartItemKind = IDL.Variant({
  'configuredKit' : ConfiguredKit,
  'singleProduct' : IDL.Record({ 'product' : Product }),
});
export const CartItem = IDL.Record({
  'id' : CartItemId,
  'kind' : CartItemKind,
  'quantity' : IDL.Nat,
  'subtotal' : IDL.Nat,
});
export const OrderId = IDL.Nat;
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'mockPaid' : IDL.Null,
});
export const ContactDetails = IDL.Record({
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const ShippingAddress = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'line1' : IDL.Text,
  'line2' : IDL.Opt(IDL.Text),
  'state' : IDL.Text,
  'pincode' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'paymentStatus' : PaymentStatus,
  'contact' : ContactDetails,
  'createdAt' : Timestamp,
  'shippingAddress' : ShippingAddress,
  'items' : IDL.Vec(CartItem),
  'subtotal' : IDL.Nat,
});

export const idlService = IDL.Service({
  '__cartItems' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(CartItem)],
      ['query'],
    ),
  '__cartState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__orderState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__orders' : IDL.Func(
      [IDL.Opt(OrderId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(OrderId, Order))],
      ['query'],
    ),
  '__products' : IDL.Func(
      [IDL.Opt(ProductId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(ProductId, Product))],
      ['query'],
    ),
  '__state' : IDL.Func([], [IDL.Reserved], ['query']),
  'addKitToCart' : IDL.Func([ConfiguredKit], [CartItemId], []),
  'addProductToCart' : IDL.Func([ProductId, IDL.Nat], [CartItemId], []),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCartSubtotal' : IDL.Func([], [IDL.Nat], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getProductsByEnvironment' : IDL.Func(
      [Environment],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'placeOrder' : IDL.Func([ContactDetails, ShippingAddress], [Order], []),
  'removeFromCart' : IDL.Func([CartItemId], [IDL.Bool], []),
  'setProductStlUrl' : IDL.Func([ProductId, IDL.Opt(IDL.Text)], [IDL.Bool], []),
  'updateCartItemQuantity' : IDL.Func([CartItemId, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CartItemId = IDL.Nat;
  const ProductId = IDL.Nat;
  const BomType = IDL.Variant({
    'kit' : IDL.Null,
    'accessory' : IDL.Null,
    'base' : IDL.Null,
    'structure' : IDL.Null,
    'wall' : IDL.Null,
    'decal' : IDL.Null,
  });
  const Scale = IDL.Variant({ 'scale1_64' : IDL.Null });
  const Category = IDL.Variant({
    'kit' : IDL.Null,
    'accessory' : IDL.Null,
    'base' : IDL.Null,
    'structure' : IDL.Null,
    'wall' : IDL.Null,
    'decal' : IDL.Null,
  });
  const Environment = IDL.Variant({
    'indianGarage' : IDL.Null,
    'indianFuelStation' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'stlUrl' : IDL.Opt(IDL.Text),
    'bomType' : BomType,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'scale' : Scale,
    'thumbnailPlaceholder' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
    'environments' : IDL.Vec(Environment),
  });
  const BomItem = IDL.Record({
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
    'totalPrice' : IDL.Nat,
    'product' : Product,
  });
  const Transform3D = IDL.Record({
    'posX' : IDL.Float64,
    'posY' : IDL.Float64,
    'posZ' : IDL.Float64,
    'rotX' : IDL.Float64,
    'rotY' : IDL.Float64,
    'rotZ' : IDL.Float64,
  });
  const KitItem = IDL.Record({
    'transform' : IDL.Opt(Transform3D),
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const ConfiguredKit = IDL.Record({
    'bom' : IDL.Vec(BomItem),
    'name' : IDL.Text,
    'scale' : Scale,
    'environment' : Environment,
    'items' : IDL.Vec(KitItem),
    'totalPrice' : IDL.Nat,
  });
  const CartItemKind = IDL.Variant({
    'configuredKit' : ConfiguredKit,
    'singleProduct' : IDL.Record({ 'product' : Product }),
  });
  const CartItem = IDL.Record({
    'id' : CartItemId,
    'kind' : CartItemKind,
    'quantity' : IDL.Nat,
    'subtotal' : IDL.Nat,
  });
  const OrderId = IDL.Nat;
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'mockPaid' : IDL.Null,
  });
  const ContactDetails = IDL.Record({
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const ShippingAddress = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'line1' : IDL.Text,
    'line2' : IDL.Opt(IDL.Text),
    'state' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'paymentStatus' : PaymentStatus,
    'contact' : ContactDetails,
    'createdAt' : Timestamp,
    'shippingAddress' : ShippingAddress,
    'items' : IDL.Vec(CartItem),
    'subtotal' : IDL.Nat,
  });
  
  return IDL.Service({
    '__cartItems' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(CartItem)],
        ['query'],
      ),
    '__cartState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__orderState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__orders' : IDL.Func(
        [IDL.Opt(OrderId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(OrderId, Order))],
        ['query'],
      ),
    '__products' : IDL.Func(
        [IDL.Opt(ProductId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(ProductId, Product))],
        ['query'],
      ),
    '__state' : IDL.Func([], [IDL.Reserved], ['query']),
    'addKitToCart' : IDL.Func([ConfiguredKit], [CartItemId], []),
    'addProductToCart' : IDL.Func([ProductId, IDL.Nat], [CartItemId], []),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCartSubtotal' : IDL.Func([], [IDL.Nat], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByEnvironment' : IDL.Func(
        [Environment],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'placeOrder' : IDL.Func([ContactDetails, ShippingAddress], [Order], []),
    'removeFromCart' : IDL.Func([CartItemId], [IDL.Bool], []),
    'setProductStlUrl' : IDL.Func(
        [ProductId, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateCartItemQuantity' : IDL.Func([CartItemId, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };