/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BomItem {
  'quantity' : bigint,
  'unitPrice' : bigint,
  'totalPrice' : bigint,
  'product' : Product,
}
export type BomType = { 'kit' : null } |
  { 'accessory' : null } |
  { 'base' : null } |
  { 'structure' : null } |
  { 'wall' : null } |
  { 'decal' : null };
export interface CartItem {
  'id' : CartItemId,
  'kind' : CartItemKind,
  'quantity' : bigint,
  'subtotal' : bigint,
}
export type CartItemId = bigint;
export type CartItemKind = { 'configuredKit' : ConfiguredKit } |
  { 'singleProduct' : { 'product' : Product } };
export type Category = { 'kit' : null } |
  { 'accessory' : null } |
  { 'base' : null } |
  { 'structure' : null } |
  { 'wall' : null } |
  { 'decal' : null };
export interface ConfiguredKit {
  'bom' : Array<BomItem>,
  'name' : string,
  'scale' : Scale,
  'environment' : Environment,
  'items' : Array<KitItem>,
  'totalPrice' : bigint,
}
export interface ContactDetails {
  'email' : string,
  'phone' : string,
  'lastName' : string,
  'firstName' : string,
}
export type Environment = { 'indianGarage' : null } |
  { 'indianFuelStation' : null };
export interface KitItem {
  'transform' : [] | [Transform3D],
  'productId' : ProductId,
  'quantity' : bigint,
}
export interface Order {
  'id' : OrderId,
  'paymentStatus' : PaymentStatus,
  'contact' : ContactDetails,
  'createdAt' : Timestamp,
  'shippingAddress' : ShippingAddress,
  'items' : Array<CartItem>,
  'subtotal' : bigint,
}
export type OrderId = bigint;
export type PaymentStatus = { 'pending' : null } |
  { 'mockPaid' : null };
export interface Product {
  'id' : ProductId,
  'stlUrl' : [] | [string],
  'bomType' : BomType,
  'name' : string,
  'description' : string,
  'scale' : Scale,
  'thumbnailPlaceholder' : string,
  'category' : Category,
  'price' : bigint,
  'environments' : Array<Environment>,
}
export type ProductId = bigint;
export type Scale = { 'scale1_64' : null };
export interface ShippingAddress {
  'country' : string,
  'city' : string,
  'line1' : string,
  'line2' : [] | [string],
  'state' : string,
  'pincode' : string,
}
export type Timestamp = bigint;
export interface Transform3D {
  'posX' : number,
  'posY' : number,
  'posZ' : number,
  'rotX' : number,
  'rotY' : number,
  'rotZ' : number,
}
export interface _SERVICE {
  '__cartItems' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<CartItem>>,
  '__cartState' : ActorMethod<[], any>,
  '__orderState' : ActorMethod<[], any>,
  '__orders' : ActorMethod<
    [[] | [OrderId], [] | [bigint]],
    Array<[OrderId, Order]>
  >,
  '__products' : ActorMethod<
    [[] | [ProductId], [] | [bigint]],
    Array<[ProductId, Product]>
  >,
  '__state' : ActorMethod<[], any>,
  'addKitToCart' : ActorMethod<[ConfiguredKit], CartItemId>,
  'addProductToCart' : ActorMethod<[ProductId, bigint], CartItemId>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCartSubtotal' : ActorMethod<[], bigint>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getProductsByEnvironment' : ActorMethod<[Environment], Array<Product>>,
  'placeOrder' : ActorMethod<[ContactDetails, ShippingAddress], Order>,
  'removeFromCart' : ActorMethod<[CartItemId], boolean>,
  'setProductStlUrl' : ActorMethod<[ProductId, [] | [string]], boolean>,
  'updateCartItemQuantity' : ActorMethod<[CartItemId, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];