/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type OrderId = bigint;
export type CartItemId = bigint;
export type Timestamp = bigint;
export interface CartItem {
    id: CartItemId;
    kind: CartItemKind;
    quantity: bigint;
    subtotal: bigint;
}
export interface BomItem {
    quantity: bigint;
    unitPrice: bigint;
    totalPrice: bigint;
    product: Product;
}
export interface ShippingAddress {
    country: string;
    city: string;
    line1: string;
    line2?: string;
    state: string;
    pincode: string;
}
export interface Order {
    id: OrderId;
    paymentStatus: PaymentStatus;
    contact: ContactDetails;
    createdAt: Timestamp;
    shippingAddress: ShippingAddress;
    items: Array<CartItem>;
    subtotal: bigint;
}
export interface ConfiguredKit {
    bom: Array<BomItem>;
    name: string;
    scale: Scale;
    environment: Environment;
    items: Array<KitItem>;
    totalPrice: bigint;
}
export type CartItemKind = {
    __kind__: "configuredKit";
    configuredKit: ConfiguredKit;
} | {
    __kind__: "singleProduct";
    singleProduct: {
        product: Product;
    };
};
export interface KitItem {
    transform?: Transform3D;
    productId: ProductId;
    quantity: bigint;
}
export interface ContactDetails {
    email: string;
    phone: string;
    lastName: string;
    firstName: string;
}
export interface Transform3D {
    posX: number;
    posY: number;
    posZ: number;
    rotX: number;
    rotY: number;
    rotZ: number;
}
export type ProductId = bigint;
export interface Product {
    id: ProductId;
    stlUrl?: string;
    bomType: BomType;
    name: string;
    description: string;
    scale: Scale;
    thumbnailPlaceholder: string;
    category: Category;
    price: bigint;
    environments: Array<Environment>;
}
export enum BomType {
    kit = "kit",
    accessory = "accessory",
    base = "base",
    structure = "structure",
    wall = "wall",
    decal = "decal"
}
export enum Environment {
    indianGarage = "indianGarage",
    indianFuelStation = "indianFuelStation"
}
export enum PaymentStatus {
    pending = "pending",
    mockPaid = "mockPaid"
}
export enum Scale {
    scale1_64 = "scale1_64"
}
export interface backendInterface {
    __cartItems(io: bigint | null, count: bigint | null): Promise<Array<CartItem>>;
    __cartState(): Promise<any>;
    __orderState(): Promise<any>;
    __orders(ko: OrderId | null, count: bigint | null): Promise<Array<[OrderId, Order]>>;
    __products(ko: ProductId | null, count: bigint | null): Promise<Array<[ProductId, Product]>>;
    __state(): Promise<any>;
    addKitToCart(kit: ConfiguredKit): Promise<CartItemId>;
    addProductToCart(productId: ProductId, quantity: bigint): Promise<CartItemId>;
    getCart(): Promise<Array<CartItem>>;
    getCartSubtotal(): Promise<bigint>;
    getOrder(id: OrderId): Promise<Order | null>;
    getProductById(id: ProductId): Promise<Product | null>;
    getProducts(): Promise<Array<Product>>;
    getProductsByCategory(category: Category): Promise<Array<Product>>;
    getProductsByEnvironment(env: Environment): Promise<Array<Product>>;
    placeOrder(contact: ContactDetails, address: ShippingAddress): Promise<Order>;
    removeFromCart(itemId: CartItemId): Promise<boolean>;
    setProductStlUrl(id: ProductId, stlUrl: string | null): Promise<boolean>;
    updateCartItemQuantity(itemId: CartItemId, quantity: bigint): Promise<boolean>;
}
import type { BomItem as _BomItem, BomType as _BomType, CartItem as _CartItem, CartItemId as _CartItemId, CartItemKind as _CartItemKind, Category as _Category, ConfiguredKit as _ConfiguredKit, ContactDetails as _ContactDetails, Environment as _Environment, KitItem as _KitItem, Order as _Order, OrderId as _OrderId, PaymentStatus as _PaymentStatus, Product as _Product, ProductId as _ProductId, Scale as _Scale, ShippingAddress as _ShippingAddress, Timestamp as _Timestamp, Transform3D as _Transform3D } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __cartItems(arg0: bigint | null, arg1: bigint | null): Promise<Array<CartItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.__cartItems(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__cartItems(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async __cartState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__cartState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__cartState();
            return result;
        }
    }
    async __orderState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__orderState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__orderState();
            return result;
        }
    }
    async __orders(arg0: OrderId | null, arg1: bigint | null): Promise<Array<[OrderId, Order]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__orders(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__orders(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async __products(arg0: ProductId | null, arg1: bigint | null): Promise<Array<[ProductId, Product]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__products(to_candid_opt_n37(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__products(to_candid_opt_n37(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async __state(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__state();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__state();
            return result;
        }
    }
    async addKitToCart(arg0: ConfiguredKit): Promise<CartItemId> {
        if (this.processError) {
            try {
                const result = await this.actor.addKitToCart(to_candid_ConfiguredKit_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addKitToCart(to_candid_ConfiguredKit_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addProductToCart(arg0: ProductId, arg1: bigint): Promise<CartItemId> {
        if (this.processError) {
            try {
                const result = await this.actor.addProductToCart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProductToCart(arg0, arg1);
            return result;
        }
    }
    async getCart(): Promise<Array<CartItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCartSubtotal(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCartSubtotal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCartSubtotal();
            return result;
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductById(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductById(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductById(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: Category): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(to_candid_Category_n51(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(to_candid_Category_n51(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByEnvironment(arg0: Environment): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByEnvironment(to_candid_Environment_n53(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByEnvironment(to_candid_Environment_n53(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: ContactDetails, arg1: ShippingAddress): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, to_candid_ShippingAddress_n61(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Order_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, to_candid_ShippingAddress_n61(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Order_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromCart(arg0: CartItemId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async setProductStlUrl(arg0: ProductId, arg1: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setProductStlUrl(arg0, to_candid_opt_n63(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProductStlUrl(arg0, to_candid_opt_n63(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCartItemQuantity(arg0: CartItemId, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCartItemQuantity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCartItemQuantity(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BomItem_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BomItem): BomItem {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_BomType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BomType): BomType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_CartItemKind_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartItemKind): CartItemKind {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_CartItem_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartItem): CartItem {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ConfiguredKit_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConfiguredKit): ConfiguredKit {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Environment_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Environment): Environment {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_KitItem_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KitItem): KitItem {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Scale_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Scale): Scale {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ShippingAddress_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShippingAddress): ShippingAddress {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transform3D]): Transform3D | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quantity: bigint;
    unitPrice: bigint;
    totalPrice: bigint;
    product: _Product;
}): {
    quantity: bigint;
    unitPrice: bigint;
    totalPrice: bigint;
    product: Product;
} {
    return {
        quantity: value.quantity,
        unitPrice: value.unitPrice,
        totalPrice: value.totalPrice,
        product: from_candid_Product_n12(_uploadFile, _downloadFile, value.product)
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    stlUrl: [] | [string];
    bomType: _BomType;
    name: string;
    description: string;
    scale: _Scale;
    thumbnailPlaceholder: string;
    category: _Category;
    price: bigint;
    environments: Array<_Environment>;
}): {
    id: ProductId;
    stlUrl?: string;
    bomType: BomType;
    name: string;
    description: string;
    scale: Scale;
    thumbnailPlaceholder: string;
    category: Category;
    price: bigint;
    environments: Array<Environment>;
} {
    return {
        id: value.id,
        stlUrl: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.stlUrl)),
        bomType: from_candid_BomType_n15(_uploadFile, _downloadFile, value.bomType),
        name: value.name,
        description: value.description,
        scale: from_candid_Scale_n17(_uploadFile, _downloadFile, value.scale),
        thumbnailPlaceholder: value.thumbnailPlaceholder,
        category: from_candid_Category_n19(_uploadFile, _downloadFile, value.category),
        price: value.price,
        environments: from_candid_vec_n20(_uploadFile, _downloadFile, value.environments)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transform: [] | [_Transform3D];
    productId: _ProductId;
    quantity: bigint;
}): {
    transform?: Transform3D;
    productId: ProductId;
    quantity: bigint;
} {
    return {
        transform: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.transform)),
        productId: value.productId,
        quantity: value.quantity
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    product: _Product;
}): {
    product: Product;
} {
    return {
        product: from_candid_Product_n12(_uploadFile, _downloadFile, value.product)
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    paymentStatus: _PaymentStatus;
    contact: _ContactDetails;
    createdAt: _Timestamp;
    shippingAddress: _ShippingAddress;
    items: Array<_CartItem>;
    subtotal: bigint;
}): {
    id: OrderId;
    paymentStatus: PaymentStatus;
    contact: ContactDetails;
    createdAt: Timestamp;
    shippingAddress: ShippingAddress;
    items: Array<CartItem>;
    subtotal: bigint;
} {
    return {
        id: value.id,
        paymentStatus: from_candid_PaymentStatus_n33(_uploadFile, _downloadFile, value.paymentStatus),
        contact: value.contact,
        createdAt: value.createdAt,
        shippingAddress: from_candid_ShippingAddress_n35(_uploadFile, _downloadFile, value.shippingAddress),
        items: from_candid_vec_n2(_uploadFile, _downloadFile, value.items),
        subtotal: value.subtotal
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: string;
    city: string;
    line1: string;
    line2: [] | [string];
    state: string;
    pincode: string;
}): {
    country: string;
    city: string;
    line1: string;
    line2?: string;
    state: string;
    pincode: string;
} {
    return {
        country: value.country,
        city: value.city,
        line1: value.line1,
        line2: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.line2)),
        state: value.state,
        pincode: value.pincode
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CartItemId;
    kind: _CartItemKind;
    quantity: bigint;
    subtotal: bigint;
}): {
    id: CartItemId;
    kind: CartItemKind;
    quantity: bigint;
    subtotal: bigint;
} {
    return {
        id: value.id,
        kind: from_candid_CartItemKind_n5(_uploadFile, _downloadFile, value.kind),
        quantity: value.quantity,
        subtotal: value.subtotal
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bom: Array<_BomItem>;
    name: string;
    scale: _Scale;
    environment: _Environment;
    items: Array<_KitItem>;
    totalPrice: bigint;
}): {
    bom: Array<BomItem>;
    name: string;
    scale: Scale;
    environment: Environment;
    items: Array<KitItem>;
    totalPrice: bigint;
} {
    return {
        bom: from_candid_vec_n9(_uploadFile, _downloadFile, value.bom),
        name: value.name,
        scale: from_candid_Scale_n17(_uploadFile, _downloadFile, value.scale),
        environment: from_candid_Environment_n21(_uploadFile, _downloadFile, value.environment),
        items: from_candid_vec_n23(_uploadFile, _downloadFile, value.items),
        totalPrice: value.totalPrice
    };
}
function from_candid_tuple_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_OrderId, _Order]): [OrderId, Order] {
    return [
        value[0],
        from_candid_Order_n31(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ProductId, _Product]): [ProductId, Product] {
    return [
        value[0],
        from_candid_Product_n12(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kit: null;
} | {
    accessory: null;
} | {
    base: null;
} | {
    structure: null;
} | {
    wall: null;
} | {
    decal: null;
}): BomType {
    return "kit" in value ? BomType.kit : "accessory" in value ? BomType.accessory : "base" in value ? BomType.base : "structure" in value ? BomType.structure : "wall" in value ? BomType.wall : "decal" in value ? BomType.decal : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scale1_64: null;
}): Scale {
    return "scale1_64" in value ? Scale.scale1_64 : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    indianGarage: null;
} | {
    indianFuelStation: null;
}): Environment {
    return "indianGarage" in value ? Environment.indianGarage : "indianFuelStation" in value ? Environment.indianFuelStation : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    mockPaid: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "mockPaid" in value ? PaymentStatus.mockPaid : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    configuredKit: _ConfiguredKit;
} | {
    singleProduct: {
        product: _Product;
    };
}): {
    __kind__: "configuredKit";
    configuredKit: ConfiguredKit;
} | {
    __kind__: "singleProduct";
    singleProduct: {
        product: Product;
    };
} {
    return "configuredKit" in value ? {
        __kind__: "configuredKit",
        configuredKit: from_candid_ConfiguredKit_n7(_uploadFile, _downloadFile, value.configuredKit)
    } : "singleProduct" in value ? {
        __kind__: "singleProduct",
        singleProduct: from_candid_record_n27(_uploadFile, _downloadFile, value.singleProduct)
    } : value;
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CartItem>): Array<CartItem> {
    return value.map((x)=>from_candid_CartItem_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Environment>): Array<Environment> {
    return value.map((x)=>from_candid_Environment_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KitItem>): Array<KitItem> {
    return value.map((x)=>from_candid_KitItem_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_OrderId, _Order]>): Array<[OrderId, Order]> {
    return value.map((x)=>from_candid_tuple_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ProductId, _Product]>): Array<[ProductId, Product]> {
    return value.map((x)=>from_candid_tuple_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BomItem>): Array<BomItem> {
    return value.map((x)=>from_candid_BomItem_n10(_uploadFile, _downloadFile, x));
}
function to_candid_BomItem_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BomItem): _BomItem {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_BomType_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BomType): _BomType {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid_ConfiguredKit_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConfiguredKit): _ConfiguredKit {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_Environment_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Environment): _Environment {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_KitItem_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KitItem): _KitItem {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_Product_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): _Product {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_Scale_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Scale): _Scale {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_ShippingAddress_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShippingAddress): _ShippingAddress {
    return to_candid_record_n62(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderId | null): [] | [_OrderId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductId | null): [] | [_ProductId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bom: Array<BomItem>;
    name: string;
    scale: Scale;
    environment: Environment;
    items: Array<KitItem>;
    totalPrice: bigint;
}): {
    bom: Array<_BomItem>;
    name: string;
    scale: _Scale;
    environment: _Environment;
    items: Array<_KitItem>;
    totalPrice: bigint;
} {
    return {
        bom: to_candid_vec_n42(_uploadFile, _downloadFile, value.bom),
        name: value.name,
        scale: to_candid_Scale_n49(_uploadFile, _downloadFile, value.scale),
        environment: to_candid_Environment_n53(_uploadFile, _downloadFile, value.environment),
        items: to_candid_vec_n55(_uploadFile, _downloadFile, value.items),
        totalPrice: value.totalPrice
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quantity: bigint;
    unitPrice: bigint;
    totalPrice: bigint;
    product: Product;
}): {
    quantity: bigint;
    unitPrice: bigint;
    totalPrice: bigint;
    product: _Product;
} {
    return {
        quantity: value.quantity,
        unitPrice: value.unitPrice,
        totalPrice: value.totalPrice,
        product: to_candid_Product_n45(_uploadFile, _downloadFile, value.product)
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ProductId;
    stlUrl?: string;
    bomType: BomType;
    name: string;
    description: string;
    scale: Scale;
    thumbnailPlaceholder: string;
    category: Category;
    price: bigint;
    environments: Array<Environment>;
}): {
    id: _ProductId;
    stlUrl: [] | [string];
    bomType: _BomType;
    name: string;
    description: string;
    scale: _Scale;
    thumbnailPlaceholder: string;
    category: _Category;
    price: bigint;
    environments: Array<_Environment>;
} {
    return {
        id: value.id,
        stlUrl: value.stlUrl ? candid_some(value.stlUrl) : candid_none(),
        bomType: to_candid_BomType_n47(_uploadFile, _downloadFile, value.bomType),
        name: value.name,
        description: value.description,
        scale: to_candid_Scale_n49(_uploadFile, _downloadFile, value.scale),
        thumbnailPlaceholder: value.thumbnailPlaceholder,
        category: to_candid_Category_n51(_uploadFile, _downloadFile, value.category),
        price: value.price,
        environments: to_candid_vec_n52(_uploadFile, _downloadFile, value.environments)
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transform?: Transform3D;
    productId: ProductId;
    quantity: bigint;
}): {
    transform: [] | [_Transform3D];
    productId: _ProductId;
    quantity: bigint;
} {
    return {
        transform: value.transform ? candid_some(value.transform) : candid_none(),
        productId: value.productId,
        quantity: value.quantity
    };
}
function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: string;
    city: string;
    line1: string;
    line2?: string;
    state: string;
    pincode: string;
}): {
    country: string;
    city: string;
    line1: string;
    line2: [] | [string];
    state: string;
    pincode: string;
} {
    return {
        country: value.country,
        city: value.city,
        line1: value.line1,
        line2: value.line2 ? candid_some(value.line2) : candid_none(),
        state: value.state,
        pincode: value.pincode
    };
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BomType): {
    kit: null;
} | {
    accessory: null;
} | {
    base: null;
} | {
    structure: null;
} | {
    wall: null;
} | {
    decal: null;
} {
    return value == BomType.kit ? {
        kit: null
    } : value == BomType.accessory ? {
        accessory: null
    } : value == BomType.base ? {
        base: null
    } : value == BomType.structure ? {
        structure: null
    } : value == BomType.wall ? {
        wall: null
    } : value == BomType.decal ? {
        decal: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Scale): {
    scale1_64: null;
} {
    return value == Scale.scale1_64 ? {
        scale1_64: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Environment): {
    indianGarage: null;
} | {
    indianFuelStation: null;
} {
    return value == Environment.indianGarage ? {
        indianGarage: null
    } : value == Environment.indianFuelStation ? {
        indianFuelStation: null
    } : value;
}
function to_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BomItem>): Array<_BomItem> {
    return value.map((x)=>to_candid_BomItem_n43(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Environment>): Array<_Environment> {
    return value.map((x)=>to_candid_Environment_n53(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<KitItem>): Array<_KitItem> {
    return value.map((x)=>to_candid_KitItem_n56(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
